version: "3.8"

services:
    # Service Aplikasi Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "8080:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=database
            - APP_KEY=base64:3Jur4YOq6Mvl20oJd4smk3VNhK/UNDyUmXFCUJMand8=
            - DB_PORT=3306
            - SESSION_DOMAIN=
            - APP_URL=http://206.189.81.234:8080
            - SESSION_DRIVER=file
            - DB_DATABASE=marketplace_kampsewa
            - DB_USERNAME=root
            - DB_PASSWORD=Kampsewa123!
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.googlemail.com
            - MAIL_PORT=587
            - MAIL_USERNAME=kampsewa@gmail.com
            - MAIL_PASSWORD=sauzmdaqtsnonfqs
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS="kampsewa@gmail.com"
            - MAIL_FROM_NAME="Kamp Sewa"
            - MIDTRANS_MERCHANT_ID=G161382177
            - MIDTRANS_CLIENT_KEY=SB-Mid-client-mg6Aw-GWdQnnwbPp
            - MIDTRANS_SERVER_KEY=SB-Mid-server-ki-ZC4CoNQXAYzeI_GPMBXBO
            - MIDTRANS_IS_PRODUCTION=false
            - MIDTRANS_IS_3DS=true
            - MIDTRANS_IS_SANITIZED=true
        networks:
            - laravel_network

networks:
    laravel_network:
        name: laravel_network
        driver: bridge
