version: "3.8"

services:
  # Service Aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=marketplace_kampsewa
      - DB_USERNAME=root
      - DB_PASSWORD=Kampsewa123!
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
